# Generated by Django 3.1.1 on 2021-09-09 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20210715_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=11)),
                ('purchaged', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_table')),
            ],
        ),
    ]
