# Generated by Django 3.1.1 on 2021-09-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_table',
            old_name='order_user',
            new_name='user',
        ),
    ]
