# Generated by Django 3.1.1 on 2021-07-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_table',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
