# Generated by Django 3.1.1 on 2021-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210706_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table',
            name='order_user',
        ),
        migrations.RemoveField(
            model_name='order_table',
            name='product',
        ),
        migrations.AddField(
            model_name='product_table',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice_table',
        ),
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
