# Generated by Django 3.1.1 on 2021-09-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20210715_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_table',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='staffImage/')),
                ('status', models.CharField(max_length=100, null=True)),
                ('Position', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('United Kingdom', 'UK'), ('United StatesOf America', 'USA')], max_length=100, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Ogun', 'Ogun'), ('Lagos', 'Lagos'), ('Kano', 'kano'), ('Abuja', 'Abuja')], max_length=100, null=True)),
                ('identification', models.ImageField(null=True, upload_to='staffImage/')),
                ('particulars', models.FileField(null=True, upload_to='staffImage/')),
                ('staff_passport', models.FileField(null=True, upload_to='staffImage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer_table',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(upload_to='staffImage/')),
                ('address', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('United Kingdom', 'UK'), ('United StatesOf America', 'USA')], max_length=100, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Ogun', 'Ogun'), ('Lagos', 'Lagos'), ('Kano', 'kano'), ('Abuja', 'Abuja')], max_length=100, null=True)),
                ('staff_passport', models.FileField(null=True, upload_to='staffImage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
