# Generated by Django 3.1.1 on 2021-09-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_table_staff_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_table',
            old_name='Position',
            new_name='position',
        ),
    ]
