# Generated by Django 3.1.1 on 2021-10-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20210928_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('United Kingdom', 'UK'), ('United StatesOf America', 'USA')], max_length=100, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Ogun', 'Ogun'), ('Lagos', 'Lagos'), ('Kano', 'kano'), ('Abuja', 'Abuja')], max_length=100, null=True)),
                ('identification', models.ImageField(null=True, upload_to='staffid/')),
                ('particulars', models.FileField(null=True, upload_to='staffid/')),
                ('profile_picture', models.ImageField(upload_to='staffImage/')),
                ('profile_passport', models.FileField(null=True, upload_to='staffid/')),
                ('position', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='staff_table',
            name='identification',
            field=models.ImageField(null=True, upload_to='staffid/'),
        ),
        migrations.AlterField(
            model_name='staff_table',
            name='particulars',
            field=models.FileField(null=True, upload_to='staffid/'),
        ),
        migrations.AlterField(
            model_name='staff_table',
            name='staff_passport',
            field=models.FileField(null=True, upload_to='staffid/'),
        ),
        migrations.DeleteModel(
            name='customer_table',
        ),
    ]
