# Generated by Django 3.1.1 on 2021-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211004_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Resigned', 'Resigned'), ('Fired', 'Fired')], max_length=100, null=True),
        ),
    ]
