# Generated by Django 3.1.1 on 2021-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211005_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
